---
- name: ansible-pull localhost playbook
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: yes

  # Roles to execute
  roles:
    - { role: base, tags: base }
    - { role: development, tags: development }
