---
  # Enable click to minimize dock panel icons
- name: gsettings|Get gnome shell dash to dock click action
  ansible.builtin.shell: gsettings get org.gnome.shell.extensions.dash-to-dock click-action
  register: click_action
  changed_when: false

- name: gsettings|Display current setting
  ansible.builtin.debug:
    msg: "click_action is: {{ click_action.stdout }}"

- name: gsettings|Set gnome shell dash to dock click to minimize
  ansible.builtin.shell: gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
  when: click_action.stdout != "'minimize'"

  # Disable USB/Removable device icons from panel
- name: gsettings|Get dock mounts icons
  ansible.builtin.shell: gsettings get org.gnome.shell.extensions.dash-to-dock show-mounts
  register: show_mounts
  changed_when: false

- name: gsettings|Display current setting
  ansible.builtin.debug:
    msg: "show_mounts is: {{ show_mounts.stdout }}"

- name: gsettings|Set dock mounts icons
  ansible.builtin.shell: gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts false
  when: show_mounts.stdout != "false"

  # Move Show Applications (dot menu on dock) to the top
- name: gsettings|Get dock show apps at top
  ansible.builtin.shell: gsettings get org.gnome.shell.extensions.dash-to-dock show-apps-at-top
  register: apps_top
  changed_when: false

- name: gsettings|Display current setting
  ansible.builtin.debug:
    msg: "apps_top is: {{ apps_top.stdout }}"

- name: gsettings|Set dock show apps at top
  ansible.builtin.shell: gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
  when: apps_top.stdout != "true"

  # Hide trash icon from the dock
- name: gsettings|Get show trash icon
  ansible.builtin.shell: gsettings get org.gnome.shell.extensions.dash-to-dock show-trash
  register: show_trash
  changed_when: false

- name: gsettings|Display current setting
  ansible.builtin.debug:
    msg: "show_trash is: {{ show_trash.stdout }}"

- name: gsettings|Set show trash icon
  ansible.builtin.shell: gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false
  when: show_trash.stdout != "false"

# Shorten dock panel to make it as compact as the amount of icons it has
- name: gsettings|Get extend-height setting
  ansible.builtin.shell: gsettings get org.gnome.shell.extensions.dash-to-dock extend-height
  register: extend_height
  changed_when: false

- name: gsettings|Display current setting
  ansible.builtin.debug:
    msg: "extend_height is: {{ extend_height.stdout }}"

- name: gsettings|Set extend-height
  ansible.builtin.shell: gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
  when: extend_height.stdout != "false"

# Move the dock panel to the bottom
- name: gsettings|Get dock-position
  ansible.builtin.shell: gsettings get org.gnome.shell.extensions.dash-to-dock dock-position
  register: dock_position
  changed_when: false

- name: gsettings|Display current setting
  ansible.builtin.debug:
    msg: "dock_position is: {{ dock_position.stdout }}"

- name: gsettings|Set dock-position
  ansible.builtin.shell: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
  when: dock_position.stdout != "'BOTTOM'"

  ##-- Keep this debug message last --##
- name: gsettings|LOG OUT NOTICE
  ansible.builtin.debug:
    msg: "LOG OUT/LOG IN for any gsettings changes to take effect."