---
- name: packages|Remove apt packages
  ansible.builtin.apt:
    name:
      - "thunderbird*"
    state: absent
    purge: yes

- name: packages|Install apt packages
  ansible.builtin.apt:
    name:
      - chrome-gnome-shell
      - flatpak
      - gnome-clocks
      - gnome-shell-extension-prefs
      - gnome-software
      - gnome-software-plugin-flatpak
      - gnome-sushi
      - gnome-tweaks
      - gnome-weather
      - python3-gpg
      - rclone
      - steam
      - tree
      - ubuntu-restricted-extras
      - vim
      - vlc
    state: present

- name: packages|Install snap packages
  community.general.snap:
    name:
      - firefox
    state: present
