---
- name: packages|Install apt packages
  apt:
    name:
      - chrome-gnome-shell
      - flatpak
      - gnome-clocks
      - gnome-shell-extension-prefs
      - gnome-software
      - gnome-software-plugin-flatpak
      - gnome-sushi
      - gnome-tweaks
      - gnome-weather
      - keepassxc
      - python3-gpg
      - steam
      - tree
      - ubuntu-restricted-extras
      - vim
      - vlc
    state: present

- name: packages|Install snap packages
  community.general.snap:
    name:
      - telegram-desktop
    state: present

- name: packages|Install dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
