---
- name: packages|Remove snap packages
  community.general.snap:
    name:
      - firefox # firefox snap does not support gnome extensions
    state: absent

- name: packages|Keepassxc PPA
  ansible.builtin.apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present

- name: packages|Mozilla Team PPA
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
    state: present

- name: packages|Install apt packages
  ansible.builtin.apt:
    name:
      - chrome-gnome-shell
      - firefox
      - flatpak
      - gnome-clocks
      - gnome-shell-extension-prefs
      - gnome-software
      - gnome-software-plugin-flatpak
      - gnome-sushi
      - gnome-tweaks
      - gnome-weather
      - keepassxc
      - python3-gpg
      - rclone
      - steam
      - tree
      - ubuntu-restricted-extras
      - vim
      - vlc
    state: present

- name: packages|Install snap packages
  community.general.snap:
    name:
      - telegram-desktop
    state: present

- name: packages|Install dropbox
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
