---
# Clojure development
- name: clojure|Check if clj is already installed
  ansible.builtin.command: which clj
  register: clj_installed
  changed_when: false
  failed_when: false

- name: clojure|Check clj version
  ansible.builtin.command: clj -version
  register: clj_version
  changed_when: false
  failed_when: false
  when: clj_installed.stdout != ""

- name: clojure|clj -version output
  ansible.builtin.debug:
    msg: "clj -version: {{ clj_version.stderr }}"
  when: clj_version.stderr is defined

- name: clojure|Download clojure installer
  ansible.builtin.get_url:
    url: https://download.clojure.org/install/linux-install-{{ clojure_version }}.sh
    dest: /home/{{ user }}/tmp/
    mode: '0755'
  register: clojure_installer
  when: (clj_installed.stdout == "") or (clojure_version not in clj_version.stderr)

- name: clojure|Execute clojure installer
  ansible.builtin.command: "{{ clojure_installer.dest }}"
  when: (clj_installed.stdout == "") or (clojure_version not in clj_version.stderr)

- name: clojure|Check if clj-new is already installed
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.command: clj -Ttools list
  register: clj_tools
  changed_when: false

- name: clojure|clj -Ttools list output
  ansible.builtin.debug:
    msg: "clj -Ttools list: {{ clj_tools.stdout }}"

- name: clojure|Install clj-new project creation tool
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.command: clojure -Ttools install com.github.seancorfield/clj-new '{:git/tag "{{ cljnew_version }}"}' :as clj-new
  when: cljnew_version not in clj_tools.stdout

- name: clojure|Check if lein is already installed
  ansible.builtin.command: which lein
  register: lein_installed
  changed_when: false
  failed_when: false

- name: clojure|which lein output
  ansible.builtin.debug:
    msg: "which lein: {{ lein_installed.stdout }}"

- name: clojure|Download Leiningen into local bin path
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /usr/local/bin/
    mode: '0755'
  when: lein_installed.stdout == ""
