---
- name: packages|Install apt packages
  apt:
    name:
      - git
      - tree
      - vim
    state: present

- name: packages|Install snap packages
  community.general.snap:
    name:
      - code
    state: present

