---
- name: packages|Install apt packages
  apt:
    name:
      - git
      - httpie
      - make
      - openjdk-11-jdk
      - rlwrap
    state: present

- name: packages|Install vscode snap package
  community.general.snap:
    name: code
    classic: yes
    state: present
