---
- name: packages|Install apt packages
  ansible.builtin.apt:
    name:
      - awscli
      - git
      - httpie
      - make
      - openjdk-11-jdk
      - python3-pip
      - rlwrap
    state: present

- name: packages|Install vscode snap package
  community.general.snap:
    name: code
    classic: yes
    state: present
